apiVersion: apps/v1
kind: Deployment
metadata:
  name: fhir-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fhir-chatbot
  template:
    metadata:
      labels:
        app: fhir-chatbot
    spec:
      containers:
      - name: fhir-chatbot
        image: docker.io/tnscorcoran/neo4j-chatbot:1.4
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        - name: VLLM_URL
          value: "https://mistral.fhir-redhat.svc.cluster.local/v1"          