apiVersion: apps/v1
kind: Deployment
metadata:
  name: fhir-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fhir-chatbot
  template:
    metadata:
      labels:
        app: fhir-chatbot
    spec:
      containers:
      - name: fhir-chatbot
        image: quay.io/tcorcoran/neo4j-chatbot
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"