apiVersion: apps/v1
kind: Deployment
metadata:
  name: fhir-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fhir-chatbot
  template:
    metadata:
      labels:
        app: fhir-chatbot
    spec:
      containers:
      - name: fhir-chatbot
        image: avijra28/chatbot:1.11
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        - name: VLLM_URL
          value: "https://mistral.fhir.svc.cluster.local/v1"
        - name: NEO4J_DEV_SERVICE_HOST
          value: "10.0.53.22"
