apiVersion: batch/v1
kind: Job
metadata:
  name: fhir-data-ingest-job
spec:
  template:
    metadata:
      name: fhir-data-ingest
    spec:
      containers:
      - name: fhir-data-ingest
        image: docker.io/tnscorcoran/neo4j-ingest:1.1
        env:
        - name: TRANSFORMERS_CACHE
          value: "/tmp/huggingface"
        - name: NEO4J_URI
          value: "bolt://172.30.210.127:30687"
        - name: NEO4J_USERNAME
          value: "neo4j"
        - name: NEO4J_PASSWORD
          value: "healthdemo"
        - name: NEO4J_DATABASE
          value: "neo4j"
        - name: EMBEDDING_MODEL
          value: "BAAI/bge-small-en-v1.5"
        - name: VLLM_URL
          value: "https://mistral.fhir-redhat.svc.cluster.local"
        - name: VLLM_MODEL
          value: "mistral"
        - name: K_NEAREST
          value: "200"
        - name: LOG_LEVEL
          value: "INFO"
        - name: S3_ENDPOINT_URL
          value: "http://minio-api-minio.apps.health.csc-sc-lab.com"
        - name: S3_ACCESS_KEY_ID
          value: "minio"
        - name: S3_SECRET_ACCESS_KEY
          value: "minio123"
        - name: S3_REGION
          value: "none"
        - name: S3_BUCKET_NAME
          value: "fhir-data"
        - name: S3_PREFIX
          value: "working/bundles/"
      restartPolicy: Never
  backoffLimit: 0
  activeDeadlineSeconds: 3600  
  ttlSecondsAfterFinished: 100
