FROM --platform=linux/amd64 registry.access.redhat.com/ubi9/python-311:1-77

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "src/ingest_data.py"]